# Generated by Django 4.1.7 on 2023-03-25 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('surname', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('speciality', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('experience', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=30, null=True)),
                ('money', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10000, null=True)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
